#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Commercial readiness rendering for SaaS acceptance page."""

from server.saas_user_pages import _h

ITEMS = [
    ('P0-1 业主与收费对象', '业主档案、收费对象、导入映射已接入。', '/backoffice/charge-targets'),
    ('P0-2 计费规则', '面积计费、固定金额、独立单价、服务期折算已接入。', '/backoffice/fee-types'),
    ('P0-3 批量出账', '按当前租户项目批量生成账单，重复账单跳过。', '/backoffice/bills'),
    ('P0-4 收款欠费', '部分收款、已收、欠费和报表联动。', '/backoffice/payments'),
    ('P0-5 收据导出', '账单/收款导出和收据详情含业务字段，不含内部字段。', '/backoffice/payments'),
    ('P0-6 导入复核', '预览不写库、错误行下载、重复对象跳过。', '/backoffice/imports'),
    ('P0-7 高风险审计', '审计风险分级、详情脱敏、租户隔离查询。', '/backoffice/audit-logs'),
    ('P0-8 备份恢复', '备份和恢复演练显示操作人、审计链路、隐藏系统路径。', '/backoffice/backups'),
    ('P0-11 商业交付演示', '新租户从空库开始，完成创建项目、收费对象、收费项目、出账、审核、收款、报表、导出、备份恢复演练。', '/backoffice/acceptance'),
    ('P0-12 最小上线包', '整理部署配置、验收演示、运维备份、上线证据；不提交真实 .env，客户上传数据与系统自身数据隔离。', '/backoffice/deploy-checklist'),
    ('P0-13 客户交付签收', '上线前人工验收，覆盖部署完成确认、数据不混用确认、客户签收和实施人员签收。', '/backoffice/acceptance'),
    ('P0-14 上线总报告', 'SaaS 云端商业版上线总报告，汇总 P0-1 到 P0-13、验证命令、部署资产、演示路径和签收路径。', '/backoffice/acceptance'),
    ('P0-15 正式报告文件', '正式 DOCX/PDF 交付版：release/saas-commercial-launch-report.docx 与 release/saas-commercial-launch-report.pdf。', '/backoffice/acceptance'),
    ('P0-16 一页式上线指引', '实施人员按执行顺序完成服务器、环境、门禁、演示、备份恢复、隔离、签收和报告留存。', '/backoffice/acceptance'),
    ('P0-17 首日巡检清单', '上线后按 T+0、T+2、T+24 巡检服务健康、权限、隔离、收费抽查、备份、日志、审计和回退观察点。', '/backoffice/acceptance'),
    ('P0-18 七日稳定复盘', '上线后第 7 日复盘业务数据、金额报表、租户隔离、权限审计、备份恢复、客户反馈，并判断是否进入下一阶段。', '/backoffice/acceptance'),
    ('P0-19 下一阶段立项决策', '7 日稳定后评估业主端 H5、微信/支付宝真实支付、授权云服务后台、更多桌面业务迁移的进入条件和边界。', '/backoffice/acceptance'),
    ('P0-20 下一阶段工单清单', '把业主端 H5 工单包、支付工单包、授权云服务后台工单包和桌面版存量业务迁移工单包拆成可执行项。', '/backoffice/acceptance'),
    ('P0-21 授权云服务边界', '建立授权云服务后台的独立服务、独立数据库、独立表结构和授权校验边界，不与 SaaS 业务主库混用。', '/backoffice/acceptance'),
    ('P0-22 授权管理后台', '授权云服务支持客户、产品、授权、授权审计的 API 和管理页面；只展示授权数据，不展示业务数据。', '/backoffice/acceptance'),
    ('P0-23 授权状态展示', 'SaaS 员工后台只读取授权云服务返回结果，展示授权状态、席位和到期时间，不暴露授权库或业务库内部字段。', '/backoffice'),
    ('P0-24 授权限制策略', '未授权或授权过期时限制高风险写入操作，保留只读查看和数据核对，不破坏租户隔离。', '/backoffice'),
    ('P0-25 授权拦截审计', '授权限制触发时记录租户范围内的 license.write_blocked 审计事件，便于商业售后和争议追踪。', '/backoffice/audit-logs'),
    ('P0-26 授权席位限制', '授权席位数与启用员工账号数联动，超过席位时限制新增或启用员工账号并记录审计。', '/backoffice/users'),
    ('P0-27 授权状态运维', '平台管理员查看各租户授权状态、席位使用数、到期时间和超限风险，不展示业务数据或授权库内部字段。', '/backoffice/license-ops'),
    ('P0-28 授权客户绑定', 'SaaS 租户必须显式绑定授权客户编号，避免靠名称匹配导致授权错绑。', '/backoffice/license-ops'),
    ('P0-29 授权绑定管理入口', '平台管理员可在授权状态运维页绑定或变更租户授权客户编号，并写入 license.tenant_bind 审计。', '/backoffice/license-ops'),
    ('P0-30 授权绑定持久化', '授权绑定关系持久化到系统侧独立 JSON 文件，不写入客户上传数据目录或 SaaS 业务表。', '/backoffice/license-ops'),
    ('P0-31 授权绑定备份恢复', '授权绑定文件可导出、恢复和校验，保障服务器迁移或重部署后绑定不丢失。', '/backoffice/license-ops'),
    ('P0-32 授权绑定运维交付', '授权绑定、备份、恢复、迁移和审计检查整理为实施人员可执行交付清单。', '/backoffice/acceptance'),
    ('P0-33 实机部署演练', '通用 Linux/VPS、腾讯云 CVM、阿里云 ECS 按接近生产的部署、登录、业务闭环、隔离、授权绑定和备份恢复完成验收。', '/backoffice/deploy-checklist'),
    ('P0-34 生产部署一键自检', '实施人员用一条自检命令检查服务器环境、端口、目录隔离、Docker Compose、Nginx、systemd、logrotate、备份恢复、授权绑定和上线证据。', '/backoffice/deploy-checklist'),
    ('P0-35 首租户初始化向导', '提供可视化登录入口和平台管理员首租户初始化向导，从客户公司、默认项目、租户管理员、授权绑定进入导入、收费项目、测试账单和隔离验收。', '/backoffice/first-tenant-wizard'),
    ('P0-37 首租户业务引导闭环', '首租户创建后提供导入模板、收费项目、测试账单、测试收款、报表、验收记录的可点击交付路径。', '/backoffice/first-tenant-wizard'),
    ('P0-38 首租户交付验收记录', '实施人员在系统内勾选首租户上线交付项，留存实施人员、客户签收人、备注和完成项摘要。', '/backoffice/first-tenant-acceptance'),
    ('P0-39 首租户验收导出打印', '首租户交付验收记录支持打印版和 HTML 导出，作为客户签收材料留存。', '/backoffice/first-tenant-acceptance'),
    ('P0-40 首租户交付包总览', '把登录、初始化向导、业务闭环、验收记录、打印导出、部署自检、备份恢复、授权绑定集中到实施人员统一入口。', '/backoffice/first-tenant-delivery-package'),
    ('P0-41 租户业务配置模板', '首租户初始化可选择住宅物业、商业/商铺、园区/办公、混合项目模板，提示字段、收费项目、账单周期和导入样例。', '/backoffice/first-tenant-wizard'),
    ('P0-42 租户业务配置持久化', '每个客户公司保存自己的业务模板配置，导入模板默认按当前租户配置展示，且不写入客户业务表或授权库。', '/backoffice/imports/templates/charge-targets'),
    ('P0-43 业务配置管理页面', '租户管理员可在后台维护本公司业务模板，普通业务角色只读查看，保存后导入模板按当前公司配置展示。', '/backoffice/tenant-business-config'),
    ('P0-44 收费项目推荐初始化', '按当前租户业务模板一键创建推荐收费项目，重复项目自动跳过，配置只作用于当前公司和项目。', '/backoffice/fee-types'),
    ('P0-45 首租户收费项目初始化交付入口', '首租户初始化向导和交付包直接提供推荐收费项目一键初始化入口，减少实施漏项。', '/backoffice/first-tenant-delivery-package'),
    ('P0-46 首租户收费项目复核验收', '首租户验收记录覆盖推荐收费项目初始化、单价复核、计费方式确认和业务模板匹配，避免金额配置漏项。', '/backoffice/first-tenant-acceptance'),
    ('P0-47 首租户验收风险提示', '首租户验收记录在完成项不足或金额配置复核未完成时提示上线风险，全部完成后显示风险解除。', '/backoffice/first-tenant-acceptance'),
    ('P0-48 首租户验收风险总览', '首租户交付包和商业验收页展示验收风险状态，实施人员在入口页即可确认风险是否解除。', '/backoffice/first-tenant-delivery-package'),
    ('P0-49 首租户验收记录持久化', '首租户交付验收记录保存到系统侧独立文件，重启后仍可读取，不进入客户上传目录或授权库。', '/backoffice/first-tenant-acceptance'),
    ('P0-50 首租户验收记录备份证据', '备份元数据显式列出首租户验收记录路径，恢复演练可验证系统侧签收证据未丢失。', '/backoffice/backups'),
    ('P0-51 首租户验收记录备份页面提示', '备份页、备份详情和恢复演练详情提示 system-files 覆盖首租户验收记录，方便实施人员现场核对。', '/backoffice/backups'),
    ('P0-52 生产环境数据库自动接入', '正式部署时 create_app 自动读取 DATABASE_URL 或 POSTGRES_* 环境变量接入 PostgreSQL，避免云端以内存模式运行。', '/backoffice/deploy-checklist'),
    ('P0-53 PostgreSQL仓储初始化兼容', '仓储初始化按数据库 dialect 生成建表和权限 upsert SQL，避免 PostgreSQL 启动时使用 SQLite 专用语法。', '/backoffice/deploy-checklist'),
    ('P0-54 PostgreSQL业务写入ID兼容', '核心业务插入按数据库 dialect 获取新记录 ID，PostgreSQL 使用 RETURNING id，SQLite 继续使用 lastrowid。', '/backoffice/deploy-checklist'),
    ('P0-55 systemd生产环境文件加载', 'systemd 服务加载 /opt/property-saas/.env，确保 VPS 启动时带上数据库、应用密钥和 SaaS 存储目录环境变量。', '/backoffice/deploy-checklist'),
    ('P0-56 生产部署实施命令', '面向通用 Linux/VPS 补齐 .env、Docker Compose、systemd、Nginx、健康检查、登录检查和上线门禁的实施命令清单。', '/backoffice/deploy-checklist'),
    ('P0-57 生产.env现场校验', '服务器部署时校验真实 .env 文件存在、权限安全、必填项齐全、密钥非占位值，并且不打印密钥原文。', '/backoffice/deploy-checklist'),
    ('P0-58 生产运行状态自检', '服务启动后检查 Docker Compose、systemd、健康接口、登录页、本机端口、Nginx 和日志目录可写。', '/backoffice/deploy-checklist'),
    ('P0-59 首租户业务冒烟', '生产启动后用首租户跑登录、收费对象、收费项目、出账、收款、报表、导出和租户隔离最小业务闭环。', '/backoffice/deploy-checklist'),
    ('P0-60 生产一键验收总入口', '串联 .env 现场校验、生产预检、运行状态、首租户业务冒烟、隔离证据和上线证据报告，减少现场漏跑。', '/backoffice/deploy-checklist'),
    ('P0-61 生产验收结果留档', '生成脱敏生产验收结果文件，记录执行人、服务器域名、检查项结果、首租户冒烟、租户隔离和签收位置。', '/backoffice/deploy-checklist'),
    ('P0-62 生产验收结果页面', '后台提供生产验收结果中心，集中查看一键验收、留档文件、上线证据、隔离证据和首租户冒烟说明。', '/backoffice/production-acceptance'),
    ('P0-63 生产验收证据摘要', '生产验收结果中心读取验收留档、上线证据、隔离证据文件状态和最近生成时间。', '/backoffice/production-acceptance'),
    ('P0-64 生产验收证据预览下载', '生产验收结果中心提供验收留档、上线证据和隔离证据的登录后预览/下载入口。', '/backoffice/production-acceptance'),
    ('P0-65 生产验收签收表', '生产验收结果中心支持填写执行人、服务器域名、客户签收人和实施人员，并生成可打印/下载的正式验收留档。', '/backoffice/production-acceptance/signoff'),
    ('P0-66 生产验收签收历史', '每次生产验收签收都保存系统侧历史记录，可在后台查看并下载指定历史留档，避免覆盖后无法追溯。', '/backoffice/production-acceptance/signoff'),
    ('P0-67 生产验收签收备份覆盖', '备份元数据、备份页面和恢复演练说明覆盖生产验收签收历史与当前验收留档，确保系统侧交付证据可恢复核验。', '/backoffice/backups'),
    ('P0-68 生产验收证据总包', '生产验收结果中心可一键下载脱敏交付证据包，包含留档、上线证据、隔离证据、签收历史和备份覆盖说明。', '/backoffice/production-acceptance'),
    ('P0-69 生产验收证据包预检', '生产验收结果中心在下载证据包前显示每个证据项存在、缺失、自动生成和是否进入总包，避免现场漏材料。', '/backoffice/production-acceptance'),
    ('P0-70 生产交付总览', '把部署自检、首租户冒烟、生产验收、证据包、签收历史和备份恢复覆盖核验整合为现场实施统一入口。', '/backoffice/production-delivery'),
]
GATES = [
    ('租户隔离证据', 'scripts/saas_isolation_evidence.py'),
    ('商业上线总门禁', 'scripts/saas_release_gate.py'),
    ('上线证据报告', 'scripts/saas_release_evidence.py'),
    ('商业验收总览检查', 'scripts/saas_commercial_readiness_check.py'),
    ('商业交付演示手册', 'docs/saas-commercial-delivery-drill.md'),
    ('商业交付演示脚本', 'scripts/saas_commercial_delivery_drill.py'),
    ('商业交付演示检查', 'scripts/saas_commercial_delivery_drill_check.py'),
    ('最小上线包清单', 'docs/saas-minimal-launch-package.md'),
    ('最小上线包检查', 'scripts/saas_minimal_launch_package_check.py'),
    ('客户交付签收清单', 'docs/saas-customer-acceptance-signoff.md'),
    ('客户交付签收检查', 'scripts/saas_customer_acceptance_signoff_check.py'),
    ('上线总报告', 'docs/saas-commercial-launch-report.md'),
    ('上线总报告检查', 'scripts/saas_commercial_launch_report_check.py'),
    ('正式报告 DOCX', 'release/saas-commercial-launch-report.docx'),
    ('正式报告 PDF', 'release/saas-commercial-launch-report.pdf'),
    ('正式报告检查', 'scripts/saas_formal_launch_report_check.py'),
    ('一页式上线指引', 'docs/saas-operator-one-page-runbook.md'),
    ('一页式上线指引检查', 'scripts/saas_operator_one_page_runbook_check.py'),
    ('首日巡检清单', 'docs/saas-day1-operations-checklist.md'),
    ('首日巡检检查', 'scripts/saas_day1_operations_checklist_check.py'),
    ('七日稳定复盘', 'docs/saas-day7-stability-review.md'),
    ('七日稳定复盘检查', 'scripts/saas_day7_stability_review_check.py'),
    ('下一阶段立项决策', 'docs/saas-next-phase-decision-checklist.md'),
    ('下一阶段立项决策检查', 'scripts/saas_next_phase_decision_check.py'),
    ('下一阶段工单清单', 'docs/saas-next-phase-issue-backlog.md'),
    ('下一阶段工单检查', 'scripts/saas_next_phase_issue_backlog_check.py'),
    ('授权云服务边界设计', 'docs/saas-license-cloud-service-boundary.md'),
    ('授权云服务边界检查', 'scripts/saas_license_cloud_boundary_check.py'),
    ('授权管理后台检查', 'scripts/saas_license_cloud_management_check.py'),
    ('授权状态展示检查', 'scripts/saas_license_status_integration_check.py'),
    ('授权限制策略检查', 'scripts/saas_license_enforcement_check.py'),
    ('授权拦截审计检查', 'scripts/saas_license_enforcement_audit_check.py'),
    ('授权席位限制检查', 'scripts/saas_license_seat_limit_check.py'),
    ('授权状态运维检查', 'scripts/saas_license_ops_page_check.py'),
    ('授权客户绑定检查', 'scripts/saas_license_tenant_binding_check.py'),
    ('授权绑定管理入口检查', 'scripts/saas_license_binding_page_check.py'),
    ('授权绑定持久化检查', 'scripts/saas_license_binding_persistence_check.py'),
    ('授权绑定备份恢复检查', 'scripts/saas_license_binding_backup_check.py'),
    ('授权绑定运维交付检查', 'scripts/saas_license_binding_runbook_check.py'),
    ('授权绑定运维交付清单', 'docs/saas-license-binding-ops-runbook.md'),
    ('实机部署演练检查', 'scripts/saas_production_deployment_rehearsal_check.py'),
    ('实机部署演练清单', 'docs/saas-production-deployment-rehearsal.md'),
    ('生产部署一键自检', 'scripts/saas_production_precheck.py'),
    ('生产部署自检说明', 'docs/saas-production-precheck.md'),
    ('首租户初始化向导检查', 'scripts/saas_first_tenant_wizard_check.py'),
    ('首租户业务引导闭环检查', 'scripts/saas_first_tenant_delivery_loop_check.py'),
    ('首租户交付验收记录检查', 'scripts/saas_first_tenant_acceptance_record_check.py'),
    ('首租户验收导出打印检查', 'scripts/saas_first_tenant_acceptance_export_check.py'),
    ('首租户交付包总览检查', 'scripts/saas_first_tenant_delivery_package_check.py'),
    ('租户业务配置模板检查', 'scripts/saas_tenant_business_template_check.py'),
    ('租户业务配置持久化检查', 'scripts/saas_tenant_business_config_check.py'),
    ('业务配置管理页面检查', 'scripts/saas_tenant_business_config_page_check.py'),
    ('收费项目推荐初始化检查', 'scripts/saas_fee_type_template_init_check.py'),
    ('首租户收费项目初始化交付入口检查', 'scripts/saas_first_tenant_fee_init_delivery_check.py'),
    ('首租户收费项目复核验收检查', 'scripts/saas_first_tenant_acceptance_fee_review_check.py'),
    ('首租户验收风险提示检查', 'scripts/saas_first_tenant_acceptance_risk_warning_check.py'),
    ('首租户验收风险总览检查', 'scripts/saas_first_tenant_acceptance_risk_overview_check.py'),
    ('首租户验收记录持久化检查', 'scripts/saas_first_tenant_acceptance_persistence_check.py'),
    ('首租户验收记录备份证据检查', 'scripts/saas_first_tenant_acceptance_backup_evidence_check.py'),
    ('首租户验收记录备份页面检查', 'scripts/saas_first_tenant_acceptance_backup_page_check.py'),
    ('生产环境数据库自动接入检查', 'scripts/saas_production_database_env_check.py'),
    ('PostgreSQL仓储初始化兼容检查', 'scripts/saas_postgres_repository_compat_check.py'),
    ('PostgreSQL业务写入ID兼容检查', 'scripts/saas_postgres_insert_id_check.py'),
    ('systemd生产环境文件加载检查', 'scripts/saas_systemd_env_file_check.py'),
    ('生产部署实施命令检查', 'scripts/saas_production_deployment_commands_check.py'),
    ('生产.env现场校验检查', 'scripts/saas_production_env_file_check.py'),
    ('生产运行状态自检', 'scripts/saas_production_runtime_check.py'),
    ('首租户业务冒烟检查', 'scripts/saas_production_first_tenant_smoke.py'),
    ('生产一键验收总入口', 'scripts/saas_production_acceptance_gate.py'),
    ('生产验收结果留档', 'scripts/saas_production_acceptance_result.py'),
    ('生产验收结果页面检查', 'scripts/saas_production_acceptance_page_check.py'),
    ('生产验收证据摘要检查', 'scripts/saas_production_acceptance_evidence_summary_check.py'),
    ('生产验收证据预览下载检查', 'scripts/saas_production_acceptance_evidence_download_check.py'),
    ('生产验收签收表检查', 'scripts/saas_production_acceptance_signoff_check.py'),
    ('生产验收签收历史检查', 'scripts/saas_production_acceptance_signoff_history_check.py'),
    ('生产验收签收备份覆盖检查', 'scripts/saas_production_acceptance_signoff_backup_check.py'),
    ('生产验收证据总包检查', 'scripts/saas_production_acceptance_evidence_package_check.py'),
    ('生产验收证据包预检检查', 'scripts/saas_production_acceptance_evidence_package_precheck.py'),
    ('生产交付总览检查', 'scripts/saas_production_delivery_overview_check.py'),
]


def render_commercial_readiness():
    item_rows = ''.join(
        f'<tr><td>{_h(name)}</td><td>{_h(desc)}</td><td><a class="ghost-link" href="{_h(href)}">检查</a></td></tr>'
        for name, desc, href in ITEMS
    )
    gate_rows = ''.join(
        f'<tr><td>{_h(name)}</td><td><code>{_h(command)}</code></td></tr>'
        for name, command in GATES
    )
    return f'''
<section class="card" style="margin-bottom:18px"><div class="card-h">商业上线总览</div><div class="card-b"><table><thead><tr><th>阶段</th><th>完成口径</th><th>入口</th></tr></thead><tbody>{item_rows}</tbody></table><div class="hint">本总览只展示业务验收项和脚本路径，不展示生产密钥、数据库密码或内部租户编号。</div></div></section>
<section class="card" style="margin-bottom:18px"><div class="card-h">上线门禁与证据</div><div class="card-b"><table><thead><tr><th>检查项</th><th>命令/资产</th></tr></thead><tbody>{gate_rows}</tbody></table></div></section>'''
